---
apb_name: nuxeo-mongodb-apb

default_debug: True
bootstrap_debug_enabled: False

# Defaults for values we could expect from a broker
_apb_plan_id: replicaset
_apb_service_class_id: 0
_apb_service_instance_id: 0

state_map:
  provision: present
  deprovision: absent
state: "{{ state_map[apb_action] }}"

cluster: kubernetes

namespace: "{{ lookup('env','NAMESPACE') | default('nuxeo', true) }}"
component: mongodb

replicas: 3
replicaSetName: "rs0"
podDisruptionBudget: {}
port: 27017
installImage_repository: k8s.gcr.io/mongodb-install
installImage_tag: 0.6
installImage_pullPolicy: IfNotPresent
image_repository: public.ecr.aws/docker/library/mongo
image_tag: 4
image_pullPolicy: IfNotPresent
podAnnotations: {}
securityContext: {}
resources: {}
persistentVolume_accessMode: ReadWriteOnce
persistentVolume_size: 5Gi
livenessProbe_initialDelaySeconds: 5
livenessProbe_timeoutSeconds: 1
livenessProbe_failureThreshold: 3
livenessProbe_periodSeconds: 10
livenessProbe_successThreshold: 1
readinessProbe_initialDelaySeconds: 5
readinessProbe_timeoutSeconds: 1
readinessProbe_failureThreshold: 3
readinessProbe_periodSeconds: 10
readinessProbe_successThreshold: 1
tls_casubjectDistinguishedName: "/CN=nuxeo-backings.mongodb.svc/OU=engineering/O=nuxeo/L=irvine/S=ca/C=us"
auth_adminUser: admin

auth_username: nuxeo
database: nuxeo